#-------------------------------------------------------------------------------
# Program: plotVarDemo.R
# Objective: draw graph of environment variable frequency
# Authors: Hackathon visualization group
# Creation: 25/03/2019
#-------------------------------------------------------------------------------

#' @title Plot Environmental Data
#' @description Hackathon function return two html plots generated by Plotly package
#' @importFrom magrittr %>%
#' @importFrom plotly layout
#' @importFrom plotly plot_ly
#' @importFrom plotly add_trace
#'
#' @param varURI  a list of two URI of the variable to plot from the \code{\link{variableList}} function or the web service directly
#' @param token a token from \code{\link{getToken}} function
#' @param wsUrl url of the webservice

#' @examples
#' \donttest{
#'  initializeClientConnection(apiID="ws_private", url = "www.opensilex.org/openSilexAPI/rest/")
#'  aToken <- getToken("guest@opensilex.org","guest")
#'  token <- aToken$data
#'  vars <- variableList(token = token)
#'  vars
#'  plotVarDemo(list(vars$value[1],vars$uri[4]), token = token)
#' }
#'
#' @export

plotVarDemo <- function(varURI, token, wsUrl = "www.opensilex.org/openSilexAPI/rest/"){
  phisWSClientR::initializeClientConnection(apiID="ws_private", url = wsUrl)

  ### Collecting Data
  variableList <- variableList(token = token, wsUrl = wsUrl)
  ## Data
  Data <- list()
  Data = lapply(varURI, FUN = function(uri){
    enviroData <- getDataVar(varURI = uri, variableList = variableList, token = token)$enviroData
    yVar <- enviroData$value
    # Casting Date in the right format
    xVar <- as.POSIXct(enviroData$date, tz = "UTC", format = "%Y-%m-%dT%H:%M:%S")
    DataX <- data.frame(date = xVar, value = yVar)
    return(DataX)
  })
  variableList <- variableList[which(variableList$uri %in% varURI), ]

  ### Plotting
  ## Theme
  # Color Palette
  colorVar <- list("#7CB5EC", "#0F528A", "#003152", "#577A003")
  colorFill <- colorVar
  for (i in 1:length(colorVar)){
    colorFill[i] <- paste(colorFill[i], "4D", sep = "")
  }
  colorBgHover <- "#F8F8F8"
  colorText <- "#525252"
  # Labels and grid
  y <- list(title = paste('<b>', variableList[1,"name"], ' (',variableList[1,"unity"], ')' , '</b>', sep = ""), color = '#282828',
            tickfont = list(family = 'serif'), gridwidth = 2)
  x <- list(title = '<b>Frequency</b>', tickfont = list(family = 'serif'), gridwidth = 2)
  title <- list(size = 20, color = '#282828', tickfont = list(family = 'serif'))

  ## Plot
  #1 improvement would be to create only one object
  # that is adapted from the number of variables we select
  i=1
  p <- plotly::plot_ly()
  # Backgound creation
  p <- plotly::layout(p, xaxis = x, yaxis = y,
                      titlefont = title,
                      margin = list(l = 60, r = 70, t = 70, b =  60))

    # Markers and Lines formatting
    nameY <- paste('y', i, sep = "")
    marker <- NULL
    marker$color <- as.character(colorVar[i])
    hoverlabel <- list(bgcolor = colorBgHover, font = list(color = colorText), hoveron = "")
    hoverlabel$bordercolor <- as.character(colorVar[i])
    # Values of the graph
    yVar <- Data[[i]]$value

    # Screening of the values without smoothing as lines

     p <- plotly::add_histogram(p,
                                x = yVar,
                                line = list(color = as.character(colorVar[i])),
                                name = variableList[i,"method"],
                                xaxis = nameY,
                                hoverlabel = hoverlabel )
     p <- plotly::layout(p, title = paste('<b>Frequency of ', variableList[i,"name"], '</b><br><i>', variableList[1,"method"], '</i>' , sep = ""))
    # 2
     i=2
     p2 <- plotly::plot_ly()
     # Backgound creation
     p2 <- plotly::layout(p2, xaxis = x, yaxis = y,
                         titlefont = title,
                         margin = list(l = 60, r = 70, t = 70, b =  60))

     # Markers and Lines formatting
     nameY <- paste('y', i, sep = "")
     marker <- NULL
     marker$color <- as.character(colorVar[i])
     hoverlabel <- list(bgcolor = colorBgHover, font = list(color = colorText), hoveron = "")
     hoverlabel$bordercolor <- as.character(colorVar[i])
     # Values of the graph
     yVar <- Data[[i]]$value

     # Screening of the values without smoothing as lines

     p2 <- plotly::add_histogram(p2,
                                x = yVar,
                                line = list(color = as.character(colorVar[i])),
                                name = variableList[i,"method"],
                                xaxis = nameY,
                                hoverlabel = hoverlabel )
     p2 <- plotly::layout(p2, title = paste('<b>Frequency of ', variableList[i,"name"], '</b><br><i>', variableList[1,"method"], '</i>' , sep = ""))
  ## Labels
  if (length(varURI) == 1){

  }
  p
  # Creation of the html object to screen in the variablesStudy
  # print(plotly::plotly_json(p))
  htmlwidgets::saveWidget(p, "plotWidget.html", selfcontained = FALSE)
  htmlwidgets::saveWidget(p2, "plotWidget2.html", selfcontained = FALSE)
  # htmlwidgets::
  # jsonlite::write_json(plotly::plotly_json(p), "plotlySchema")
  # jsonlite::write_json(jsonlite::fromJSON(plotly::plotly_json(p)), "plotlyData")
  # jsonlite::write_json(Data,"gridData")
  #return(Data)
}
